package com.jtouzy.cvapi.dao.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface DAOTableIDField {
	public boolean autoGenerated() default false;
}
